---
title: "Causality and Ceramics in Maluku, Indonesia"
author: "Lauryl Zenobi"
date: "June 6 2015"
output: rmarkdown::tufte_handout
---
#Introduction  
The focus of this paper is Chung Ching Shiung's dissertation, which explores changes in ceramic assemblages in the Maluku region of Indonesia. A copy of his dissertation has been uploaded to the source folder on github. Shiung's dissertation was selected because of its focus on ceramics and its comprehensive nature, as it will be of direct influence on my own research. The goal of this exercise is to both delve into the existing literature on Maluku ceramic industries, to explore Shiung's theoretical frameworks in the hope that it will inform my own interpretations, and to connect Shiung's research to the current literature on explantory theory. 

This dissertation, titled, "The Implications of Social, Cultural, Economic, and Political Interactions for Ceramic Evolution on the Banda Islands, Maluku Province, Indonesia", explores the relationships between external factors like culture contact and trade, and internal factors like changes to cultural material. The research goals of Shiung's dissertation are to determine:  
  1) whether the external and internal factors affect Banda’s material culture, particularly its ceramics   
  2) how we can measure and monitor their influence on Banda’s ceramic changes, and   
  3) the broader implications of ceramic changes in connection with Banda’s cultural history [@Shiung_2011]

#Archaeological evidence 
Ceramic materials are the unit of analysis for this dissertation. Shiung argues that ceramic assemblages could be used to understand the social, political, and economic rationale of the people who produce and distribute the ceramics. Previous approaches, such as Bellwood's Austronesian expansion model has long been used to explain the movement and distribution of people and goods (utilitarian and trade) throughout Island Southeast Asia (ISEA).   
Ceramics remained largely unchanged for millenia in ISEA, however, the development of pan-regional trade with Chinese and Muslim traders during the past one thousand years may have disrupted this continuity. If that is true, then increased culture contact as a result of growing trade relationships could induce changes in local material culture. Shiung focuses particularly on the specialization of ceramic production in the Banda Islands in the context of a growing maritime spice trade during the last one thousand years in the Maluku region. Specifically, this study looks at changes in lip-rim thickness of ceramics vessels as its proxy for specialization.

The earliest pottery in this region dates to about 3400 BP [@Shiung_2011]. Around 3000 BP changes in temper style, a decline in exterior decoration and slip, and changes to the style of rims occurs in the Banda Islands. Convex lip rims are the most common lip rim style during the lower periods of occupations at all the sites. Everted lip rims are prevelant throughout occupation, indicating that although some styles faded in and out, the assemblages as a whole remain remarkably consistent. One of the relevant changes for this study is the shift towards burnished lip rims during the 6th to 16th centuries, which Shiung attributes to cultural diffusion between the Banda Islands and North Maluku [@Shiung_2011]. 

In Pulau Ay, there is no evidence for foreign earthenware, so this shift to a North Maluku style of lip rim is likely a result of people moving across the landscape, rather than simple exchange of materials [@Shiung_2011]. The appearance of lime tempers in parts of Maluku at this time is also attributed to the movement of people and their associated pottery production methods. The local quartz temper remains in use at several sites in Pulay Ay and Banda Neira, suggesting the two tempers could be used to indicate social boundaries, sinnce the external morphology of the ceramics became increasingly similar [@Shiung_2011]. 

Aside from the shift towards a North Maluku lip design, Shiung was unable to find strong evidence to support his hypothesis of craft specialization in Banda Islands ceramics. Intra-regional trade and the movement of people across the landscape likely brought new production methods, but despite foreign contact during the 6th to 16th centuries as a result of early nutmeg trade, ceramics in the Banda Islands remained an inalienable product. 

#Link between evidence and behavior 
It is expected that as specializaton increases, there will be a corresponding reduction in variation of lip-rim thickness within the recovered ceramic assemblages. Ethnographic evidence demonstrates that ceramic specialization has occurred in Maluku during the past few centuries [@Shiung_2011]. Shiung proposes that social boundaries and trade networks are mechanisms that could affect ceramic assemblages [@Shiung_2011]. However, these behaviors often do not present archaeologically.  Behaviors like culture, society, contact, adaptation, migration, and specializaton do not always produce concrete traces that can be empirically measured, as such, they could be ephemeral mechanisms [@Glennan_2010]. Ceramics, however, are a useful way of answering these questions because of their multiple levels of function and style, their ubiquity and durability, and the fact that both the production and distribution of ceramics can leave evidence in the archaeological record. Mechanisms for cultural change can be inferred from this archaeological proxies. 

#Different scales of behavior  
Shiung proposes that social networks and social boundaries may be mechanisms that would impact the variation of a ceramic assemblage. Discovering these mechanisms can be accomplished by tracing the historical context of the spice trade in Maluku [@Shiung_2011], so as to uncover potential causal processes that affected ceramic assemglabes.  
The written history of Maluku is somewhat patchy and often filled with contradiction, but it is clear that Maluku was in contact with western Indonesia, and in particular, Java, by at least the 13th century. This contact likely continued up to the Colonial Period and the expansion of the global spice trade [@Shiung_2011]. This implies that eastern Indonesia, and Maluku, was the center of eastern Indonesian products for Java and western Indonesia. As a result, it is very likely that specific regions or ports within eastern Indonesia became important loci for this trade network [@Shiung_2011]. 
The creation of spice plantations during the Colonial Period undoubtedly interrupted any local ceramic production in the Banda Islands. During this period Banda became increasingly dependent on imported goods, with labor focused on the **perkebun** (spice plantations) established by the Dutch East Indies (VOC). Local ceramic production during the Colonial Period, therefore, were discouraged and it is not likely that any local Bandanese ceramics will be visible in the archaeological record of that time [@Shiung_2011].   
It is less clear how the 16th century conversion to Islam affected local ceramic production and trade in Maluku. Both Javanese communities and eastern Indonesian communities in Maluku participated in this conversion [@Shiung_2011], so it is possible that ceramic production was not heavily impacted by this phenomena. 

#Explanatory model  
Shiung employs a causal explanatory model to explore the relationship between cultural material, trade goods, and social and economic contexts in which changes to those archaeological proxies will occurr. Shiung's causal model calls for a causal interpretation of ceramics, paying particular attention to the historical, economic, social and cultural contingencies of the Maluku region. In particular, this means understanding changes to ceramic production and styles within the context of existing local trade as well as the emergence of more regional and global trade. Carnelian beads in Maluku, for example, were first import goods. However, eventually these beads were produced locally rather than imported [@Shiung_2011]. Therefore, interpreting all Carnelian beads as evidence of foreign trade and "Indianization" ignores the more intricate causal mechanisms and context of the event.

The primary goal of Shiung's model is to uncover the causal mechanisms behind any potential changes to ceramics assemblages in Maluku. Shiung is primarily interested in what external or internal factors could motivate any changes to the ceramic assemblages, stating that "[i]gnoring local developments prevents us from revealing the “black box” and leaves the mechanisms of cultural evolution a mystery” [@Shiung_2011]. 

#Explanatory model and relevant philosophy of science literature   
Causality is an essential ingredient in scientific explanation, and both causal and statistical relationships are necessary to provide full scientific explanations [@Salmon_1997]. A causal process is characterized by the change of a structure in a temporal and spatial sense, in other words, a causal process involves mechanisms that are able to influence components of the process to produce a certain result. In order to provide useful answers, scientific explanation must cite at least some portion of a causal process or interaction [@Woodward_1989]. Causality supplies the "story" behind the explanation, essentially supplying the interesting "why" of a question about a phenomena [@vanFrassen_1980]. In the case of Shiung's research, the causal process of gradually increasing trade and the movement of people across the social landscape of Indonesia provides the answer to the question of why ceramics in Maluku exhibit very little change over time. 

Salmon believes we gain greater insight by looking at causality at a higher theoretical level, while remembering that the abstract must eventually be applied to the real world, and that there are many empirical ways of looking at this. An object must be present in order to be part of a process, or to be a mechanism within that process [@Salmon_1997]. Social sciences must often make use of ephemeral mechanisms, abstract mechanisms within a causal process that are only sporadically observed, and may leave very little evidence outside of the result of that process. These mechanisms are common in archaeology because of the generally low resolution of our data, and must then be inferred from the cultural material - the archaeological proxies. In this case, Shiung infers cultural mechanisms that would explain the lack of change in pottery production from the ceramic assemblages. 

The causal character of archaeological explanation has to be taken in conjunction with a recognition of the basic statistical character of explanations in the sciences. This is relevant to archaeology, in which probablistic relationships are important means of understanding a variety of social phenomena, the effectiveness of a specific hunting strategy for example, or the probability of the development of social stratification [@Salmon_1992]. The statistical nature of Shiung's research lends itself well to Salmon's model of explanation, in that the causal relationships of changes to Maluku ceramic assemblages is supported by the statistical data he collected during his analysis of rim sherd variation.  

Critiques of Salmon's Causality (or Causal Nexus approach) have focused on potential limitations of looking at phenomena in a mechanistic sense, particularly in regards to complex phenomena. Causal processes are most clearly articulated in simple systems, to which Salmon's approach seems very appropriate. In complex systems, it becomes difficult to trace the causal factors within a causal process, as more interactions are required and in which multiple causal processes may be occurring [@Woodward_1989]. 
Woodward believes that complex systems should be first understood as various levels of organizations, to which different levels of explanations are applied. This is because causality may be able to explain things on the macro-scale, but at the micro-scale the causal process falls apart and fails to explain the particularities of the phenomenon (Woodward 1989). Interestingly, other authors have criticized Salmon's causality for failing to account for macro-level explanations. These criticisms have resulted in the development of higher type-level models of explanation, such as unificatinism and mechanistic models [@Kitcher_1989],[@Glennan_2010]. 

Even Hempel, known for his deductive model of explanation which draws heavily from generalizable laws, has acknowledged the utility of causal processes in explanatory theory [@Kuznar_2008]. Although causality does occasionally utilize generalizable laws to explain the mechanisms of causal factors, it does not rely on natural laws or theories that would limit its ability to explain social phenomena, which have already been acknowledged to be largely ephemeral. Woodward (1989) has also criticized Salmon for relying on statistical information in the creation of an explanation, and for assuming that a single mode of explanation is capable of explaining all phenomena in both the natural and social sciences. However, as noted previously, archaeological proxies are often the only evidence of abstract social behaviors. Statistical analyses are often the most informative data that can be extrapolated from archaeological materials. Ceramics, in particular, in the case of Shiung's work, lend themselves well to morphological and quantitative analyses.

Regardless of these criticisms, many believe that causality is an important component of any form of explanation, and is useful in providing additional flexibility to archaeological explanations [@Kuznar_2008]. 

#Critique of Shiung's model    
An ontic approach, in which the explanation is characterized by its content, [@Wylie_2002] provides causal mechanisms. Every suitable explanation must cite causal mechanisms in at least some part of the explanation [@Woodward_1989]. Even if deficient, the use of an explanation style that relies on causal mechanisms, such as Salmon causality or Van Frassen's pragmatism, allows the archaeologist to pinpoint areas of explanatory weakness [@Woodward_1989]. Shiung's original hypothesis, that changes to ceramic lip rim thickness could indicate craft specialization, was rejected. Shiung was unable to determine that ceramics changed significantly over time or in a way that was expected were craft specialization a factor. 

This explanation is generative, in that it may not provide the complete story, but it nonetheless helps to explain the unexpected lack of overall change to Maluku ceramics, yet accounts for the slight changes to lip style and temper type that are noted in the assemblages. 

#Conclusion    
Shiung's research demonstrates how causal processes can be applied to social phenomena at both the small scale and larger regional scale in Maluku, Indonesia. Criticisms of the Causal-Nexus approach argue that this mode of explanation cannot fully explain a phenomena, however it is clear from Shiung's work that he himself recognizes that he explanation may not be the entire story. Rather, causality allows the researcher to be flexible in exploring the mechanisms that caused social change. In the case of Shiung's dissertation, causality allows him to explore the external factors that may have caused a lack of change to ceramic assemblages. 

Shiung's explanation that the movement of people across Maluku resulted in small changes to temper type and lip style over time, and in some way may have buffered any trend towards or incentive for craft specialization and production of ceramics in the context of foreign contact and external trade does not curtail future research. Rather it provides an interesting conundrum. What other causal processes or factors may have been present that could account for the persistence of cultural materials despite the availability of foreign goods and technology? Shiung's explanation provides additional lines of research that can be explored. Instead of providing entire explanations, the Causal-Nexus approach allows scientific exploration to go on little by little, and provides the opportunity to question social phenomena more fully. 











